name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: creating custom tag
      run: SOURCE_COMMIT=$(git rev-parse HEAD)
    - name: Build the Docker image
      run: docker build -t ${{SOURCE_COMMIT}}
