name: Render Deploy

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]
  workflow_run:
    workflows: ["Docker Image Build and Push"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
